"use client";

/**
 * B-roll Library — every cutaway clip the system has paid to generate
 * (Runway / Higgsfield), plus manual uploads, in one reusable pool.
 *
 * Generated insert clips are auto-filed here by the render pipeline; the
 * matcher reuses a strongly matching clip on future renders instead of
 * spending credits to regenerate it ("reused" tags count how often a clip
 * earns its keep). Everything here is also available as a clip source in
 * the timeline editor.
 */

import { useEffect, useRef, useState } from "react";
import { api, mediaUrl, type MediaAsset } from "@/lib/api";
import { Button, Card, CardTitle, Spinner, PageHeader, Badge } from "@/components/ui";
import { MediaTabs } from "@/components/media-tabs";

export default function BrollLibraryPage() {
  const [clips, setClips] = useState<MediaAsset[]>([]);
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState<string | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);

  async function load() {
    try {
      const r = await api.listMedia("broll");
      setClips(r.media);
      setErr(null);
    } catch (e) {
      setErr(e instanceof Error ? e.message : "load failed");
    } finally {
      setLoading(false);
    }
  }
  useEffect(() => {
    load();
  }, []);

  async function onUpload(files: FileList | null) {
    if (!files || files.length === 0) return;
    setBusy(true);
    setErr(null);
    try {
      for (const f of Array.from(files)) {
        await api.uploadMedia(f, "broll", { title: f.name });
      }
      await load();
    } catch (e) {
      setErr(e instanceof Error ? e.message : "upload failed");
    } finally {
      setBusy(false);
      if (fileRef.current) fileRef.current.value = "";
    }
  }

  async function remove(id: string) {
    try {
      await api.deleteMedia(id);
      setClips((c) => c.filter((m) => m.id !== id));
    } catch (e) {
      setErr(e instanceof Error ? e.message : "delete failed");
    }
  }

  const reuseCount = (m: MediaAsset) =>
    (m.tags || []).filter((t) => t === "reused").length;
  const engineOf = (m: MediaAsset) =>
    (m.tags || []).find((t) => t === "runway" || t === "higgsfield");

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Media Library"
        sub="Reusable B-roll pool. Clips generated by Runway / Higgsfield are filed here automatically; upload your own footage too. Future renders reuse a matching clip instead of paying to regenerate it, and everything here is available in the timeline editor."
      />
      <MediaTabs />

      <Card>
        <CardTitle>Upload B-roll</CardTitle>
        <p className="text-[12px] text-muted-foreground mb-3">
          Drone shots, property walk-throughs, street footage, stock clips —
          anything worth cutting away to. Give files descriptive names
          (e.g. <i>staten-island-brownstone-aerial.mp4</i>): the reuse matcher
          and the editor search both read the title.
        </p>
        <input
          ref={fileRef}
          type="file"
          multiple
          accept="video/*"
          onChange={(e) => onUpload(e.target.files)}
          className="block w-full text-[12px] text-muted-foreground file:mr-3 file:py-1.5 file:px-3 file:rounded-md file:border-0 file:bg-primary file:text-primary-foreground file:cursor-pointer"
        />
        {busy && <p className="text-[12px] mt-2"><Spinner /> uploading…</p>}
        {err && <p className="text-[12px] mt-2 text-destructive">✗ {err}</p>}
      </Card>

      {loading ? (
        <div className="text-muted-foreground text-sm flex items-center gap-2"><Spinner /> loading…</div>
      ) : clips.length === 0 ? (
        <Card>
          <p className="text-[13px] text-muted-foreground">
            No B-roll yet. Clips appear here automatically the next time a
            video render animates its cutaways — or upload footage above.
          </p>
        </Card>
      ) : (
        <Card>
          <CardTitle>Clips ({clips.length})</CardTitle>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3 mt-2">
            {clips.map((m) => {
              const n = reuseCount(m);
              const engine = engineOf(m);
              return (
                <div
                  key={m.id}
                  className="border border-border rounded-md overflow-hidden bg-background flex flex-col"
                >
                  <video
                    src={mediaUrl(m.uri)}
                    controls
                    preload="metadata"
                    className="w-full aspect-[9/16] object-cover bg-black"
                  />
                  <div className="p-2 flex flex-col gap-1.5">
                    <div className="text-[11px] leading-snug line-clamp-2">{m.title || "(untitled)"}</div>
                    <div className="flex flex-wrap items-center gap-1">
                      {engine && <Badge tone="accent">{engine}</Badge>}
                      {(m.tags || []).includes("generated")
                        ? <Badge tone="muted">generated</Badge>
                        : <Badge tone="ok">upload</Badge>}
                      {n > 0 && <Badge tone="primary">reused ×{n}</Badge>}
                    </div>
                    <button
                      onClick={() => remove(m.id)}
                      className="text-[11px] text-muted-foreground hover:text-destructive text-left"
                    >
                      delete
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </Card>
      )}
    </div>
  );
}
