// In-app tutorials, keyed by route. PageHeader auto-renders a
// "How it works" button for any route present here (see
// components/help-drawer.tsx). Adding a tutorial = one entry here;
// no page edits. Content is written to match what each tool ACTUALLY
// does — keep it honest. Drafted by reading each page 2026-06-13.

export type Tutorial = {
  title: string;
  what: string; // one plain sentence: what this tool does
  when?: string; // when to use this vs a sibling tool
  steps: string[]; // imperative how-to, in order
  tips?: string[]; // gotchas / good-to-know, grounded in real behavior
};

export const TUTORIALS: Record<string, Tutorial> = {
  "/analytics": {
    title: "Analytics",
    what: "A performance dashboard that shows how your brand's own social accounts are doing — total followers, posts, and engagement across every platform you've connected.",
    when: "Use Analytics to track how YOUR content is performing; for competitor and peer comparisons, go to Market Research instead.",
    steps: [
      "Open Analytics. The top of the page shows your live totals — followers, posts, accounts, and platforms — pulled together across every connected account, with a breakdown by platform and a per-account table below.",
      "If you see \"No accounts connected yet,\" click the \"Connect accounts in Settings\" link and add your Meta token or PostProxy key, then come back — the numbers fill in automatically.",
      "In the \"Connected accounts · live\" card, click any profile to expand it and load its recent posts; click a post thumbnail to open it in a new tab. Hit \"Refresh\" to re-pull the latest.",
      "To track a public handle without connecting it, open \"Manage tracked handles,\" pick a platform, type the handle (no @), and click \"+ Add account.\"",
      "With at least one handle added, click \"Refresh from social\" to pull its recent posts via the public scrape — give it a moment to finish.",
      "Use the Account / Platform / time-window filters and the \"Sort by\" menu to explore your summary cards, breakout post, daily-views chart, top posts, and the side-by-side account leaderboard.",
    ],
    tips: [
      "Live follower counts can be incomplete — not every platform reports them, so totals show a \"≥\" sign when they're only partial, and a dash (—) means no number was available.",
      "The two panels are different: \"Connected accounts · live\" uses your authenticated Meta/PostProxy keys (real numbers), while \"Manage tracked handles\" just scrapes public posts for any handle you list. Only handles you add there get scraped.",
      "Watch the provider badges (✓ / ✗ / —) and any \"expires in Nd\" warning on a profile — if a connection key isn't set up or is expiring, reconnect it in Settings or your numbers will stop updating.",
      "If \"Top posts\" is empty, widen the time window (7/30/90/365 days) or run a refresh — only handles that have been scraped will show data.",
    ],
  },
  "/audio": {
    title: "Audio Library",
    what: "A shelf for the background music and sound effects your videos use — you upload audio clips and label them so renders can grab the right sound automatically.",
    when: "Use this when you want your videos to have music or whoosh transitions; it only stores and tags audio — the actual videos get built on the render/video pages.",
    steps: [
      "Need clips first? Use the 'Free sources to fill the library' links at the top to download royalty-free music and sound effects, watching the license note on each.",
      "In the 'Music beds' box, click the file picker and choose one or more audio files to upload them (you can also drag in several at once).",
      "On each uploaded track, click ONE mood pill — upbeat, calm, dramatic, or tension — so renders wanting that mood can find it.",
      "In the 'SFX' box, upload short sound effects (clips of about one second or less work best).",
      "Tag each sound effect with its kind; pick 'whoosh' for the swooshes used on B-roll transitions.",
      "To swap a track, click its mood/kind pill again to clear it, or click 'delete' to remove the clip entirely.",
    ],
    tips: [
      "Untagged audio is invisible to renders — any track without a mood (or sound without a kind) shows a red 'untagged — not used' badge and will never play.",
      "Mood and kind tags are one-at-a-time: clicking a second pill clears the first, so each clip has a single label.",
      "Today only the 'whoosh' kind is wired up — it drops automatically at every B-roll cutaway. Other kinds (hit, riser, pop) are stored but not used yet.",
      "Watch the license column: most sources need no credit, but Incompetech/CC-BY tracks require an attribution line wherever you publish.",
    ],
  },
  "/autopilot": {
    title: "Autopilot",
    what: "Autopilot invents fresh, on-brand content ideas in James's voice, drafts them as reels or text posts, and drops every piece into your Approval Queue for review.",
    when: "Use Autopilot when you want a batch of ready-to-review content generated for you automatically; use the Video Studio instead when you need one specific video with full control (your own footage, your own script, an avatar).",
    steps: [
      "In the 'Create now' card, pick what you want: Videos (reels with voice and captions), Text posts (written posts with an AI image), or Mix (half and half).",
      "Choose how many pieces to make by tapping a number (5, 7, 10, 14, 30) or typing your own (1-50) - roughly that many days of content.",
      "Click the Generate button and let it work in the background; pieces appear one by one as they finish.",
      "Open the Approval Queue to review, edit, and approve each piece - nothing posts anywhere on its own.",
      "(Optional) In 'Daily schedule', flip the toggle to Enabled, set pieces-per-day and a run hour, and click Save so a small batch is created automatically each day.",
      "(Optional) In 'Content defaults', set your platforms, video styles, caption mode, B-roll engine, and a topic hint, then Save - these apply to every batch.",
    ],
    tips: [
      "Nothing ever publishes itself. Every generated piece lands in the Approval Queue and waits for you to approve it.",
      "The daily schedule only runs while the server is up (it runs in-process), and it does nothing until you flip it to Enabled - but the 'Create now' button always works regardless.",
      "Generation happens in the background and reels take real time to render, so pieces show up gradually; watch the 'Recent runs' card to see progress (drafted vs. queued) and any errors.",
      "Only the first platform you select is used per piece, and if your chosen B-roll engine is missing its key/credits, that clip keeps a still image instead of failing the render.",
    ],
  },
  "/brand": {
    title: "Brand Voice & Rules",
    what: "This page is where you set your brand's voice, rules, and on-screen branding — everything here gets baked into every AI answer and every video the system makes for you.",
    when: "Use this page to teach the system how your brand should sound and look; use it before generating content elsewhere, since these rules are applied automatically to everything.",
    steps: [
      "Fill in your Brand Kit at the top: your display name, tagline, and social handle, then upload a logo image — these become the name plate, watermark, and 'Follow for more' end card on every video. Click Save brand kit.",
      "To add a written rule, scroll to 'Add a voice rule', pick a Type (identity, guideline, protocol, framework, or frustration), give it a short Name, type the actual rule in Content, and click 'Add to brand rules'.",
      "To teach from a document, drag a file into the 'Ingest a brand document' box (or click to browse) — it accepts .txt, .md, .pdf, .docx, and audio like .mp3/.m4a/.wav. The file is read and folded into your brand voice automatically.",
      "Check the 'Rules governing the voice now' list at the bottom to confirm everything you added is active.",
    ],
    tips: [
      "Everything on this page is loaded into the AI on every single answer and cannot be overridden by a prompt — so only put rules here you truly want enforced every time.",
      "Leave a Brand Kit field empty to skip that element; with no logo uploaded, the watermark and end-card logo are simply left off your videos.",
      "Audio files are transcribed (via Whisper) before being added, so an uploaded voice memo or recording becomes searchable brand memory just like a text document.",
      "Use the 'frustration' type for things to NOT do or past mistakes — it's the spot for 'never say this' kinds of rules.",
    ],
  },
  "/broll": {
    title: "B-roll Library",
    what: "A shared pool of cutaway video clips — the short shots your videos cut away to (drone aerials, walk-throughs, street footage) — holding both clips the system generated automatically and footage you upload yourself.",
    when: "Use this tab to stock and manage reusable cutaway clips; use the Hero Library for photos and videos of your brand's spokesperson, or the Reference Library for style references.",
    steps: [
      "Open the B-roll Library tab inside Media Library.",
      "Under 'Upload B-roll', click the file picker and choose one or more video files (you can select several at once — videos only).",
      "Give each file a clear, descriptive name before uploading, like 'staten-island-brownstone-aerial.mp4' — the system searches clips by their title.",
      "Wait for the 'uploading…' spinner to finish; your clips then appear in the grid below, each with a small preview you can play.",
      "Check the badges on each clip: 'upload' (yours) vs 'generated', the engine that made it (Runway or Higgsfield), and 'reused ×N' showing how often it's been reused.",
      "To remove a clip you no longer want, click 'delete' under it.",
    ],
    tips: [
      "You don't have to upload everything — clips are filed here automatically the next time a video render creates its cutaways, so the library fills itself over time.",
      "Naming matters: the reuse matcher and the timeline editor's search both read the file's title, so vague names like 'clip1.mp4' make a clip hard to find and reuse.",
      "Good names save money — when a future video needs a matching shot, the system reuses a clip from here instead of paying credits to generate a new one (that's what the 'reused' count tracks).",
      "Delete is immediate and removes the clip from the shared pool — there's no undo, so only delete footage you're sure you won't need in future videos.",
    ],
  },
  "/design-studio": {
    title: "Content Studio",
    what: "Content Studio turns one idea into ready-to-post text written in your brand voice, scores each draft on how on-voice it is, and drops everything into your Approval Queue.",
    when: "Use this when you want written posts and captions; use Multi-platform mode to spin one topic into several channels at once, or Single draft mode when you want full control over one specific piece.",
    steps: [
      "Pick a mode at the top: Multi-platform (one idea into several channels) or Single draft (one focused piece).",
      "Type your Topic, what the content should be about, this is the only required field.",
      "In Multi-platform, tap the channel chips (LinkedIn, Facebook, Instagram, X, TikTok) to choose where it goes, and leave '+ carousel' on if you want a slide carousel too.",
      "Optionally add a Pillar (which brand pillar it supports) and Extra instructions for a one-off steer; in Single draft you can also set Platform, Format, and a research subject to ground the facts.",
      "Click Generate, then wait while it writes and voice-checks each draft.",
      "Review the draft cards: each shows a voice score, and you can copy the text or export it as a .txt file.",
      "Open the Approval Queue (the 'Review in the queue' link) to approve before anything goes anywhere.",
    ],
    tips: [
      "Nothing publishes from here. Every draft is queued for approval and shows '{n} queued for approval', so you still have to approve it in the Queue before it's used anywhere.",
      "Multi-platform runs take roughly 30 to 60 seconds because it writes and voice-QA-checks each piece in parallel, so don't refresh while the spinner is up.",
      "Watch the voice score on each card: green is on-voice, yellow is so-so, red means it drifted, and the 'voice-QA' line lists exactly what slipped so you know what to fix.",
      "The Generate button stays disabled until you enter a Topic, and a card marked 'not generated' means that piece was skipped, check its note for why.",
    ],
  },
  "/editor": {
    title: "Timeline Editor",
    what: "A simple video editor where you stitch together clips you've already uploaded or rendered, add captions, transitions, a logo, sound effects, and a background music mood, then render one finished video.",
    when: "Use this when you want to hand-assemble a video from existing clips in a specific order; use the other producers when you want the system to generate a video from a script or topic instead.",
    steps: [
      "Fill in the Project box at the top: give it a Title, pick a background music mood, and choose your Platform (Instagram, TikTok, YouTube, LinkedIn) and Aspect (9:16, 16:9, 1:1).",
      "On the left under Library, browse your clips (use the dropdown to filter to Reference uploads, Scene clips, or Finished videos) and click any clip to add it to your timeline. You can also paste an https video URL into 'Paste any URL' and click 'Add to timeline'.",
      "For each block on the timeline, open it and set the duration, transition (cut/fade/slide), an optional logo overlay corner, an on-screen caption, mute the clip's own audio, or add an SFX sound URL. Use the up/down arrows to reorder, the copy icon to duplicate, and the X to remove.",
      "Check the '~Xs total' estimate next to the Render button so you know roughly how long the finished video will be.",
      "Click 'Render [N] blocks'. Watch the Render card show the status (queued, planning, assembling, succeeded), then click 'Review in Approval Queue' when it finishes.",
    ],
    tips: [
      "Every clip must be a publicly reachable https link. Clips marked 'local' are greyed out and can't be added; if a block shows a red warning, re-upload that clip through the Reference Library first or the render won't start.",
      "Nothing gets published. A finished render lands in the Approval Queue for review, where you can preview it and approve or reject it.",
      "Renders take a few minutes and the page checks for progress automatically every couple of seconds. The background music mood applies as a single track across the whole video, not per clip. Video assembly needs a Creatomate API key configured on the backend, or the render will fail.",
    ],
  },
  "/engaging-video": {
    title: "Engaging Reel",
    what: "Turns a script into a vertical video where James talks to camera the whole time, with a handful of cinematic B-roll images cutting in at the moments the AI thinks land best.",
    when: "Use this when you want James on screen for most of the video with image cutaways as punctuation; pick Story Reel/mix instead when you want the time split roughly 50/50 between James and B-roll.",
    steps: [
      "Type a topic in the first box (e.g. 'how I knew the deal that would change my life'), pick your Platform and Aspect (9:16 for Instagram/TikTok), then click 'Auto-generate script' — or skip straight to writing your own.",
      "Read and edit the script in box 2; every word here is exactly what James will say out loud. The little counter shows the rough length in seconds.",
      "Pick an Image style for the B-roll cutaways (or leave 'Story default' to let the system choose), then pick a Caption style (or leave 'AI pick' to match the script's energy).",
      "Click 'Make engaging reel' and leave the page open while it works.",
      "Watch the status badge move through 'rendering avatar' to 'stitching'; cutaway thumbnails appear as their images generate, and the finished video plays right on the page.",
      "When it's done, click 'Review in Approval Queue' to approve it — nothing gets posted automatically.",
    ],
    tips: [
      "Renders take about 2-3 minutes. The page checks for progress every few seconds on its own, so just wait — don't refresh or click the button again (it stays disabled while a render is running).",
      "Nothing publishes. The finished reel lands in the Approval Queue for you to review and approve before it goes anywhere.",
      "You can't produce without a script — if box 2 is empty you'll see 'Add a script first.' Auto-generate needs the brand voice and live research wired up; if a step like script generation or B-roll fails, the error shows in red and the badge turns to 'failed'.",
      "Past engaging reels show up under 'Recent engaging reels' at the bottom — click any one to reopen it and replay the video or see its cutaways.",
    ],
  },
  "/hero": {
    title: "Hero Media Library",
    what: "It stores photos (and clips) of your brand's hero — the recurring person in your content — so the system can describe them and reuse that same face consistently across AI-generated story reels and talking videos.",
    when: "Use this to set up your brand's hero once; the description it builds feeds the story/reel and image tools elsewhere so they stop generating random AI strangers.",
    steps: [
      "Make sure the 'Photos' tab is selected, then upload 3-8 clear photos of your hero (face, build, signature look) from different angles and lighting.",
      "Wait for the 'Hero description' card to fill in — the system reads your photos and writes a short description of the person. Read it to confirm it 'sees' your hero correctly.",
      "Add more photos any time, or hit 'Re-describe' to rebuild the description from your current photos.",
      "To make a talking video, scroll to 'Clone the hero into a talking video', pick 'Topic' (it writes the script for you) or 'Paste a script', type your text, choose an aspect ratio (9:16, 1:1, or 16:9), and click 'Generate talking clone'.",
      "Find your finished talking video in the Output Library, and review/approve it in the Approval Queue before anything goes out.",
      "(Optional) In 'Higgsfield Soul IDs', click 'Find my Soul IDs' to list trained characters from your connected Higgsfield account and copy an ID.",
    ],
    tips: [
      "Photos are the engine: without hero photos, the description and the talking-clone won't work, and story-mode reels will fall back to generic AI faces. The 'Generate' button stays disabled until you've uploaded photos.",
      "Nothing publishes automatically — a generated talking video renders in the background and lands in the Approval Queue / Output Library for you to check first.",
      "The 'Videos' tab is reserved for a future feature and is NOT used by the current image generator, so for now upload photos, not clips.",
      "Higgsfield Soul IDs only work if your Higgsfield API key and secret are set under Settings → API connections; otherwise you'll see a 'not set' error.",
    ],
  },
  "/heygen-video": {
    title: "HeyGen Video",
    what: "It turns a script into a single talking-head video of James's avatar speaking your words end-to-end, with captions burned in, and drops it into your Approval Queue.",
    when: "Use this when you want one clean avatar speaking straight to camera with no B-roll or scene cuts; use the mixed-mode video pipeline instead when you want images, clips, and scene changes.",
    steps: [
      "Type a topic in the Topic box (for example, why Staten Island is underpriced for commercial RE) and pick your Platform (Instagram, TikTok, YouTube, or LinkedIn) and Aspect (9:16 for vertical, 16:9 for wide, 1:1 for square).",
      "Click Auto-generate script to have it research and write one continuous script in your brand voice, or skip that and paste your own script into the Script box.",
      "Read the script in box 2 carefully and edit it freely — every word there is exactly what the avatar will say out loud, so this is your last chance to fix it.",
      "Click Make HeyGen video and wait while the status badge moves through queued, planning, rendering, and assembling (roughly 1 to 3 minutes).",
      "When it shows succeeded, watch the preview that appears, then click Review in Approval Queue to send it on — nothing goes live on its own.",
    ],
    tips: [
      "Nothing publishes from this screen. Every finished video lands in the Approval Queue for you to review and approve before it goes anywhere.",
      "The video reads your script word for word, so typos, wrong street names, or awkward phrasing get spoken exactly as written — proofread box 2 before producing.",
      "Renders take a few minutes, and the Make button is locked while one is in progress; leave the page open until the badge says succeeded or failed.",
      "This page only ever makes a single avatar talking straight to camera — no images, B-roll, or scene cuts — and the little character/seconds counter is just a rough length estimate.",
    ],
  },
  "/images": {
    title: "Post Images",
    what: "Generates a single clean, AI-made hero image for a social post from a topic you type, then saves it to your image library so any post can reuse it.",
    when: "Use this when you need a fresh, on-brand image to illustrate a post; use the upload-based media tools instead when you already have your own photo or graphic to add.",
    steps: [
      "In the 'Describe the post' box, type your Topic — the subject of the image, e.g. 'why Staten Island commercial RE is underpriced' (this field is required).",
      "Optionally add a Brief: paste your draft post or describe the angle you want the image to evoke.",
      "Pick the Platform (LinkedIn, Twitter, Instagram, or Facebook) — it sets the default shape; only set Aspect if you want to override that default.",
      "Tap a Style pill — photoreal for buildings and real scenes, editorial for concepts, minimal for bold thumbnails, b&w photo for a serious look.",
      "Click 'Generate image' and wait about 10–25 seconds for it to appear under 'Latest' and in your Library.",
      "Use 'Copy URL' to grab the image link, click the image to open it full-size, or 'Delete' to remove it.",
    ],
    tips: [
      "Each generation makes one clean image with no text, logos, or collages on purpose — write any headline yourself afterward.",
      "Image generation runs on OpenAI's gpt-image-1, so an OpenAI API key must be configured or generation will fail with an error.",
      "Every image is saved to the shared Library and stays there until you delete it — and Delete is permanent, with no undo, so be sure before confirming.",
    ],
  },
  "/jp-clips": {
    title: "Reference Library",
    what: "A place to store the brand's reference videos — your own talking-head clips, example videos you want to copy the style of, and extra B-roll footage — so the video pipeline has real material to draw from.",
    when: "Use this tab for video footage that drives the look and feel of generated videos; use the Hero Library tab for photos and videos of the brand's face, and the Audio Library for music and sound effects.",
    steps: [
      "Pick a category at the top: James's clips (your real talking-head footage), Style references (videos you want to copy), or B-roll (extra footage to mix in).",
      "Click \"Upload video(s)\" to add files from your computer (you can select several at once), or paste a YouTube, Drive, or CDN link in the box and click \"Add link\".",
      "For an uploaded video, click \"analyze\" on its tile — the system watches it and fills in a \"What it sees\" summary (hook, pacing, captions, look) plus tips on what to replicate.",
      "Add or edit your own style notes in the box on each tile — say what you want copied (hook, pacing, captions). Notes save automatically when you click away.",
      "On a James's clip, use \"mute audio\" if you want the clip to show on screen but have a narrator track supply the voice instead of its own sound.",
    ],
    tips: [
      "Analysis only runs on uploaded videos, not on pasted links — the \"analyze\" button only appears on files you upload.",
      "After you hit analyze, the tile shows \"analyzing…\" and the page refreshes itself every few seconds until it's done, so give it a moment.",
      "Notes can be auto-filled by the analysis but you can always overwrite them — the system keeps whatever you type.",
      "Delete asks you to confirm, but there's no undo once a clip is removed from the library.",
    ],
  },
  "/jp-live": {
    title: "JP Live",
    what: "A read-only status page that shows you what's genuinely connected and working in your brand system right now — which integrations are live, which social accounts are linked, and when your content was last pulled in.",
    when: "Use this as your quick \"is everything plugged in and running?\" health check; it only reports status, so go elsewhere in the dashboard to actually upload content, connect accounts, or ask questions.",
    steps: [
      "Open JP Live to load the live status of your brand system — the page fills itself in automatically, there are no buttons to press.",
      "Check the Integrations section: each tag shows a tool's state — 'live' means it's connected and running, 'configured' means it's set up but not yet active, and a dash means it isn't set up.",
      "Check Social connections to see each platform, the handle linked to it, and whether it's 'configured' or still pending.",
      "Read the Memory section to see the date and time of the last ingest event — that's the most recent time the system pulled your content in.",
      "Refresh the page anytime you want the latest status.",
    ],
    tips: [
      "This page shows status only — you can't upload, connect accounts, or change settings here. Those live on other pages.",
      "It intentionally hides views, follower growth, and reach. The system isn't wired to a social-metrics source yet, and it won't make up performance numbers.",
      "If a section shows dashes or stays empty, that means nothing is connected or set up yet — it's not an error.",
      "A blank or '—' Last ingest event just means no content has been pulled in yet.",
    ],
  },
  "/library": {
    title: "Output Library",
    what: "One shelf for every finished piece of content — your rendered video reels plus the approved text posts paired with the images the system made for them — where you can watch, download, copy, and sign off on each one.",
    when: "Use this to view and grab your finished work; to actually make new content go to Long Form Cutter, Engaging Reel, or Video Studio, and to approve text drafts go to the Approval Queue.",
    steps: [
      "Open the Output Library — finished videos and approved posts load together.",
      "Use the top tabs (All, Videos, Posts) to choose what you see; for videos, narrow further with the Filter and Review chips.",
      "Click play on any video to watch it right there, or click a post's image to open it full-size.",
      "Grab what you need: Download or Copy URL on videos, Copy text or Download image on posts.",
      "On a video that hasn't been reviewed yet, click Approve, or click Reject and type why it's wrong, then submit.",
    ],
    tips: [
      "A reject reason is required — blank rejections won't submit. Whatever you write gets saved and the system reads it on the next render so it avoids the same mistake. Click 'Learned ... items' to see what it's already picked up.",
      "This page is view-only — it never deletes or re-renders anything. To change or remake a video, go to Video Studio (the pipeline page).",
      "Only finished videos show up here (the ones that rendered successfully), and only text posts you've already approved in the Approval Queue. If it's empty, nothing has finished or been approved yet.",
      "Once you approve or reject a video, that choice sticks — there's no un-review button, so make the call deliberately.",
    ],
  },
  "/long-form": {
    title: "Long Form Cutter",
    what: "It takes a long podcast, interview, or talking-head video and automatically finds the best 30-45 second moments to turn into short vertical Reels.",
    when: "Use this when you have one long recording you want chopped into several short clips; if you already have a short clip that's good as-is, use \"Render whole as reel\" instead of waiting for candidate picks.",
    steps: [
      "Add your video one of three ways: click a tile in 'Pick from Drive folder', paste a sharable Drive link and hit Import, or use 'Or upload a file' to upload from your computer. A title is optional.",
      "Wait while it processes. The status badge moves through uploading, transcribing, then analyzing, and the page refreshes itself every few seconds until it says 'ready'. Long files (up to about an hour) are fine.",
      "Click your source in the Sources list to open it. You'll see a handful of suggested clips, each with a score, a time range, the standout quote, and a short summary.",
      "Pick your look from the dropdowns at the top: caption style (leave on 'Auto-pick' to let it choose), B-roll engine, and pacing.",
      "Click 'Render reel' on the clips worth keeping, and hit the small '✕' to dismiss ones you don't want. If you'd rather post the whole clip as one Reel, click 'Render whole as reel'.",
      "Each render goes to the Approval Queue to finish in the background. Click the 'Approval Queue' link in the popup (or 'rendering →' on the clip) to check on it and approve.",
    ],
    tips: [
      "Nothing ever publishes on its own. Every render lands in the Approval Queue for you to review first.",
      "Renders happen in the background and take a few minutes each, so you don't have to wait on the page.",
      "Drive imports only work if the file (or folder) is shared with your account's service-account email, set up in Settings. If a folder looks empty, that sharing step is usually why.",
      "If no clips come back, or you don't like the picks, click 'Re-analyze' to have it try again, or just use 'Render whole as reel'.",
      "B-roll never breaks a render: if the chosen engine's keys or credits aren't set up, those cutaways simply keep a still image instead of moving footage.",
    ],
  },
  "/market-research": {
    title: "Social Research",
    what: "Tracks the creators and competitors you watch, surfaces what's going viral in your space, and runs live web research — saving the useful bits to memory so the rest of the app can cite them.",
    when: "Use this to find content ideas and peer intel; switch to the Approval Queue to actually review and ship anything a \"Make script\" button creates here.",
    steps: [
      "In the Watchlist, pick a platform (Instagram, TikTok, or YouTube), type a creator's @handle or channel, and click Add to start tracking them.",
      "Click 'Refresh feed' (or 'Refresh now' on the roster) to pull their recent posts immediately — otherwise they're scraped automatically once a week.",
      "On the 'Trend radar' tab, type a topic or hashtag like 'home staging' or 'NYC apartments', choose which platforms to scan, and click 'Discover viral content' to see posts ranked by outlier score (biggest break-out first).",
      "On any trend card, click 'Make script' to have the app write a short script from that post in your brand voice.",
      "Switch to the 'Topic research' tab, enter a subject (and an optional focus), and click 'Research' to get a live web summary with findings and source links.",
    ],
    tips: [
      "Nothing here publishes. A generated script is saved to the Approval Queue with a voice score, and a human has to approve it before anything ships.",
      "Refreshing isn't instant — it kicks off a scrape in the background, so you'll see a 'check back in a minute' note and need to reload to see new posts.",
      "'Make script' only works on trends already saved to memory, so run a Discover (or a feed refresh) first — otherwise it'll tell you the trend isn't saved yet.",
      "Topic research needs a Perplexity API key set in Settings. Without one you'll get a placeholder 'stub' result instead of real internet intelligence.",
    ],
  },
  "/pipeline": {
    title: "Video Studio",
    what: "Video Studio turns a topic or a script into a finished social video — it plans the scenes, renders the clips (avatar, B-roll, your own footage), stitches them into one cut, and drops it in your Approval Queue for review.",
    when: "Use this to make a video. Pick Composer to start from a trending topic, From script to turn a written script into video, or Single clip to render one short AI clip from a text prompt.",
    steps: [
      "Choose a tab at the top: Composer (start from a topic and let it build scenes), From script (paste a script you already have), or Single clip (one short clip from a text description).",
      "In Composer, type a topic like 'Staten Island commercial real estate' and click Compose to auto-build a scene plan; in From script, paste your script and pick the platform (Instagram, TikTok, YouTube, LinkedIn) and aspect ratio (9:16, 16:9, 1:1).",
      "Use Preview plan (From script) to see the scene-by-scene breakdown before committing, or review and tweak the scenes in Composer.",
      "Click Produce video to render and assemble the full cut — the progress bar walks through planning, rendering clips, assembling, and succeeded.",
      "When it finishes, play the preview and click 'Review in approval queue' to send it on for sign-off; for Single clip, write a prompt, add the required still-image URL, and click Submit render.",
    ],
    tips: [
      "Nothing publishes from here — every finished video lands in the Approval Queue for review before it goes anywhere.",
      "It runs in 'stub' mode out of the box: you'll get a placeholder result, not a real MP4, until render keys (HeyGen voice_id + a Creatomate key) are configured. Stub videos are clearly labeled.",
      "Producing takes a few minutes — the page polls and updates the status bar on its own, so leave it open and wait rather than re-clicking Produce.",
      "Single clip requires a still-image URL (Runway's API needs it), and that field is ignored only when running in stub mode.",
    ],
  },
  "/profile": {
    title: "Profile",
    what: "Your account settings page — see your login details, manage which social handles your workspace tracks, change your password, and jump to where your API keys live.",
    when: "Use this for personal and workspace settings; for the full numbers behind your social handles go to Analytics, and for actual API key entry go to Settings (API connections).",
    steps: [
      "Check your account details at the top — your email, display name, role, and workspace id are shown here for reference.",
      "Under 'Brand accounts', pick a platform (Instagram, TikTok, or YouTube), type the handle without the @, and click '+ Add' so analytics and autopilot know what to track.",
      "Remove a handle anytime by clicking the small ✕ next to it.",
      "To change your password, fill in your current password, then your new password twice, and click 'Change password'.",
      "Click 'Open API connections →' to go to the Settings page where you enter keys for OpenAI, Anthropic, HeyGen, and the rest.",
      "Use 'Sign out' when you're done to safely log out of your workspace.",
    ],
    tips: [
      "Your new password must be at least 10 characters and the two new-password boxes have to match, or you'll get an error before anything saves.",
      "Your email, display name, and workspace id are display-only here — you can't edit them on this page.",
      "Adding or removing handles here is the same list Analytics uses — it's just a quick shortcut; the full view lives on the Analytics page.",
      "API keys aren't entered on this page — this page only links you to the Settings page where they're stored, encrypted, and take effect on the next request with no restart needed.",
    ],
  },
  "/queue": {
    title: "Approval Queue",
    what: "A review desk where every piece of content the AI proposes — finished videos, reels, captions, and post drafts — waits for your yes or no before it goes anywhere.",
    when: "Use this when you want to check, approve, or reject AI-made content; the other tools (Long Form Cutter, Engaging Reel, Content Studio, Autopilot) are where you create the content that lands here.",
    steps: [
      "Open the queue — it lands on the Pending pile by default. Use the four cards up top (Pending, Approved, Rejected, Total) to switch which pile you're looking at.",
      "Pick a tab — Videos, Posts, or All — to focus on one kind of content. Finished videos play right on the card, so watch before you decide.",
      "Read the item, then click Approve to keep it or Reject to send it back. Use the small Delete (trash) link only when you want it gone for good.",
      "When you reject, type a short reason why (for example 'too salesy' or 'wrong tone') and click Confirm rejection — that reason trains the engine.",
      "For approved items, grab them: videos get a Download link, scripts get a 'Make video →' button, and posts get copy or download .txt buttons.",
    ],
    tips: [
      "Nothing here publishes anywhere — approving just marks it as good and unlocks the download/copy actions. You still post it yourself.",
      "Reject vs Delete are different: rejecting keeps the item and teaches the system from your reason, while Delete erases it permanently with no learning and can't be undone.",
      "Your rejection reasons pile up in the 'What the engine has learned' list at the bottom and become hard rules the AI won't break in future drafts.",
      "Approving a finished video pops a note pointing you to the Output Library — that's where its download lives.",
    ],
  },
  "/settings": {
    title: "Settings",
    what: "Settings is where you feed the brand manager its memory and connection info: your API keys, your brand documents (sorted into categories), hard voice rules, your profile, and your social handles.",
    when: "Use Settings to set up and teach the brand manager before generating content; use the content tools elsewhere to actually create posts.",
    steps: [
      "In 'API keys & connections', paste any keys you have (Perplexity, Google Search, OpenAI, etc.) into the matching boxes, then click 'Save'. They take effect on the next request, no restart needed. Click 'Test live connections' to confirm each one shows 'ok'.",
      "Under 'Brand guidance - by category', find the right category card (Founder thesis, Brand guidelines, Frustration ledger, Voice corpus, or Reference) and drag in or choose your files. They just stage at first - nothing is sent yet.",
      "Click the 'Upload' button on that card to actually send the staged files. Wait for each to show a green check with its chunk count.",
      "In 'Strict voice rules', pick a Type, give the rule a Name and a Rule body, then click 'Add rule' for any non-negotiable (like banned phrases or your voice spine).",
      "Fill in 'Profile' with your brand, operator name, and email, then click 'Save profile'.",
      "Under 'Social connections', type each platform's @handle, tick 'on' for the ones you use, and click 'Save connections'.",
    ],
    tips: [
      "Files don't upload when you drop them - they only stage. You must click the 'Upload' button on the card to send them.",
      "Re-uploading a file with the same name into the same category replaces the old version - the previous content is retired and only the latest is used (old copies are kept for audit but never reused).",
      "'Save connections' only stores your handle and on/off switch - it does NOT actually post to any platform. Real posting is a separate build that isn't wired up here.",
      "Strict voice rules are loaded into the model on every answer and can't be overridden by a prompt, so use them only for true non-negotiables.",
    ],
  },
  "/social-companion": {
    title: "Social Companion",
    what: "Social Companion lets you keep a watchlist of creators and competitors, pull their recent posts ranked by what's breaking out, and turn any standout post into an on-brand script for your review.",
    when: "Use this when you want to watch what specific creators are posting and borrow their winning formats; use Trend Radar instead when you want to discover fresh ideas by topic rather than by a named list of people.",
    steps: [
      "Pick a platform from the dropdown (Instagram, etc.), type a creator's @handle or channel name, and click Add (or press Enter) to put them on your watchlist.",
      "Repeat to build a list of competitors or creators whose style you want to learn from; each person you track appears as a card you can edit.",
      "Click Refresh feed to pull their recent posts right now — they come back as cards ranked by how far each post broke out (the 'outlier' score) and how fast it's growing.",
      "Skim the cards, open any post with 'view original' to watch it, then click Make script on the one you want to turn into content.",
      "Read the generated script and its voice score, then find it in the Approval Queue to approve, edit, or discard it.",
    ],
    tips: [
      "Nothing publishes automatically — every script you make lands in the Approval Queue, where a human approves it before anything ships.",
      "Refresh feed stays greyed out until you've added at least one creator. If you skip refreshing, new handles still get picked up on the next weekly scrape.",
      "Make script only works on posts the system has saved (you'll see an error like 'this trend isn't saved to memory yet' otherwise) — refreshing the feed first is what saves them.",
    ],
  },
  "/social-listening": {
    title: "Social Listening",
    what: "Searches what people are posting about any topic, competitor, or your own brand across X, Instagram, TikTok, and Reddit \u2014 and shows you who's talking and how much engagement it's getting.",
    when: "Use this to monitor brand mentions and competitor buzz in real time across all four platforms at once; use Analytics for your own connected accounts' numbers, and Social Research for tracking specific influencers over time.",
    steps: [
      "Check the Xpoz account card at the top \u2014 it shows your plan and how many credits you have left this month.",
      "Type what you want to monitor in the search box: a topic, your brand name, or a competitor.",
      "Pick which platforms to include (X, Instagram, TikTok, Reddit) and how many results per platform, then click Search.",
      "Read the summary cards \u2014 total mentions, total engagement, and which platform is loudest \u2014 plus the by-platform bars and the single top mention.",
      "Scroll the Mentions list to see each post with its author, likes, comments, and a link to the original.",
    ],
    tips: [
      "Each search spends Xpoz credits, so the result count you pick (5/10/20 per platform) draws from your monthly quota \u2014 watch the credits-left number on the account card.",
      "Results are sorted by engagement (most likes first), so the posts that matter most are at the top.",
      "Keyword search is broad \u2014 a generic term pulls in loosely-related posts; use a specific brand name or phrase for tighter results.",
      "If a platform shows an error in the Mentions header, the others still return \u2014 one platform failing never blocks the rest.",
    ],
  },
  "/story-mix": {
    title: "Story Reel (Mix)",
    what: "It turns a short script into a single edited reel that cuts between James talking on camera and AI-made photo stills, all under one continuous voiceover.",
    when: "Use this when you want a polished, edited-looking reel that mixes James's face with B-roll visuals; use Story Video instead if you want only AI photo stills with no on-camera face.",
    steps: [
      "Type a topic in box 1 (for example, 'why Staten Island commercial RE is underpriced'), pick your platform and aspect ratio, then click Auto-generate script — or skip the topic and paste your own script.",
      "Read the script in box 2 and edit it freely. James will say these exact words out loud, so this is your final wording.",
      "In box 3, pick an image style for the B-roll stills (or leave 'Story default' to get cinematic), and in box 4 pick a caption style (or leave 'AI pick' to let it choose).",
      "Click 'Make story reel' and wait — the status badge and the picture grid fill in as it works, marking each beat as 'avatar' (James on camera) or 'B-roll' (a still).",
      "When the badge says 'done', play the finished reel, then click 'Review in Approval Queue' to send it for sign-off.",
    ],
    tips: [
      "Nothing posts automatically — every finished reel lands in the Approval Queue for you to review before anything goes out.",
      "Renders take a few minutes; the page checks for progress every couple of seconds, so leave it open and watch the badge and grid update.",
      "You can't click Make story reel until there's a script in box 2 — if it's empty you'll see 'Add a script first.'",
      "The system decides which lines show James's face versus a photo (personal and emotional lines get his face; facts, numbers, and locations get a still) — you don't choose this per line.",
      "Past reels show under 'Recent story reels' at the bottom; click any one to reopen and replay it.",
    ],
  },
  "/story-video": {
    title: "Story Video",
    what: "It turns a short script into a finished social video — James's cloned voice reading your words over a slideshow of AI-generated photo-real images, with on-screen captions and music, all timed to the exact words spoken.",
    when: "Use this when you want a narrated \"talking story\" video built from a script with auto-generated images; use the avatar or other video modes instead when you want James on camera or a hand-built scene timeline.",
    steps: [
      "Type a topic in box 1 (like 'why Staten Island commercial real estate is underpriced'), pick your platform and aspect ratio, then click 'Auto-generate script' — or skip the topic and paste your own script into box 2.",
      "Read box 2 and edit it freely — James speaks every word here exactly as written, and the little counter shows the rough spoken length.",
      "In box 3 pick an image style and in box 4 pick a caption style (leave either blank to let it choose a sensible default for you).",
      "Click 'Make story video' in box 5 and leave the page open while it works.",
      "Watch the status badge and the grid of images fill in as each one is generated; when it says 'done', the finished video appears so you can play it.",
      "Click 'Review in Approval Queue' to find it later — nothing goes out until you approve it there.",
    ],
    tips: [
      "Each render takes about 3 to 5 minutes and runs through several services (voice, image, stitching), so keep the tab open and be patient — the button stays disabled while one is in progress.",
      "Nothing ever publishes automatically. Every finished video lands in the Approval Queue for you to review first.",
      "If you see a red error, it usually means a connected service (voice, images, or video) isn't set up or hit a snag — check that the underlying API keys are configured before retrying.",
      "Your last several story videos are listed at the bottom; click any one to reopen it and replay it without starting over.",
    ],
  },
  "/style-templates": {
    title: "Style Templates",
    what: "It turns reference videos you've uploaded into reusable \"style recipes\" — capturing the layout, captions, logo, pacing, and sound — so you can produce a brand-new video in that same trending style.",
    when: "Use this when you want to copy the look and feel of a video you admire; use the Media Library to upload the reference clip first, since templates only get built from uploaded style references.",
    steps: [
      "Upload a reference video first under Media Library, Style references tab. It gets inspected automatically and shows up here.",
      "If a clip is sitting under \"Reference videos awaiting a template,\" click \"Inspect, build template\" to have it studied and turned into a style.",
      "Wait for a template to reach the \"ready\" status, then read its summary, quick-fact pills, and \"What makes it distinctive\" notes to confirm it's the style you want.",
      "Click \"Replicate this style\" on that template to open the producer panel.",
      "Choose your output (Avatar replica or a 20-second B-roll reel), then either type a topic (it writes the script in your voice) or paste your own finished script.",
      "Pick your platform, aspect ratio, and B-roll engine, then click \"Produce video\" and follow the \"Watch it render in Output Library\" link to see it finish.",
    ],
    tips: [
      "Inspection and producing take time. The page auto-refreshes every few seconds while anything is still being inspected, and you must enter a topic or script before \"Produce video\" will run.",
      "Only uploaded clips can become templates. Reference videos added by URL can't be inspected, and \"inspection failed\" can appear, just click Inspect again to retry.",
      "Nothing is final on this screen. \"Produce video\" sends the render to your Output Library, and the panel will list what it could only \"approximate\" from the original. Deleting a template keeps the underlying reference video safe.",
      "If your chosen aspect ratio differs from how the reference was filmed, the style is still reproduced. A note tells you the shape will change but the layout, captions, and pacing carry over.",
    ],
  },
  "/updates": {
    title: "What's Changing Next",
    what: "It turns your feedback and notes on videos and captions into a plain-English roadmap of changes, sorted into what's already applied, what's queued for the next build, and what's shipped.",
    when: "Use this after you've been rejecting or commenting on videos and captions and want to see how that feedback is being acted on; it's a read-and-track board, not where you give feedback in the first place.",
    steps: [
      "Open the page to see your roadmap, split into three groups: Applied live, Queued for the next build, and Shipped.",
      "Click '↻ Refresh from latest feedback' to have it read your newest notes and rejections and turn them into changes.",
      "Check the 'Applied live' group for small tweaks (struck through) that took effect instantly, no action needed.",
      "In 'Queued for the next build', review each bigger change and the note it came from; click 'mark shipped' once a change has gone live, or 'dismiss' to drop one you don't want.",
      "Look at the 'Shipped' group to confirm what's already been delivered.",
    ],
    tips: [
      "Nothing here happens on its own — you only see new changes after you click Refresh, which re-reads your latest feedback.",
      "Each item shows the area it touches and the exact note it came from (e.g. 'from: ...'), so you can trace why a change was made.",
      "Refresh is safe to click repeatedly — it won't create duplicates, it just re-reads and updates the board.",
    ],
  },
  "/video": {
    title: "Video Studio",
    what: "A single home page that lists every video-making tool as a card, grouped by what you already have, so you can jump to the right one.",
    when: "Start here whenever you want to make a video but aren't sure which maker to use; the actual uploading and rendering happens on the tool you click into, not on this page.",
    steps: [
      "Decide what you're starting with: existing footage (a podcast, interview, or recorded clip), just a script (words, no footage), or a finished idea you want to assemble by hand.",
      "Scan the matching section: 'From existing footage', 'From a script', or 'Power tools' for manual control.",
      "Read each card's one-liner and the italic 'Best for' line to find the maker that fits your situation. If unsure, pick the one marked 'Most common' (Long Form Cutter).",
      "Click the card to open that maker, where you'll actually upload your clip or paste your script and start the video.",
      "Follow that maker's screen to render your video.",
    ],
    tips: [
      "This page only points you to the right tool, it doesn't make anything itself. Nothing uploads or renders until you click into a card.",
      "Renders happen on the next screen and take a few minutes; finished videos don't auto-publish, they land in your Approval Queue for review.",
      "Some makers rely on outside services (like HeyGen avatars or AI B-roll) that need an API key set up first, so if a feature looks blank, the key may not be configured yet.",
    ],
  },
  "/voice-studio": {
    title: "Voice Studio",
    what: "Voice Studio pulls in your brand's own talks, podcasts, posts, and documents from Google Drive, turns them into text, and feeds them into your brand voice so every draft sounds more like you.",
    when: "Use this to teach the system how your brand sounds (or what it believes / its writing rules) by importing source material from Drive; it's a one-way import, not a place to write or publish content.",
    steps: [
      "Paste a Google Drive folder link in the top box, or drop one or more individual file links (one per line) in the box below it — you can use either or both.",
      "Open the 'Ingest as' dropdown and pick what the material is: Voice corpus (how the brand sounds), Thesis (what the brand believes), Guidelines / voice rules, or Reference (facts, not voice).",
      "Click 'Ingest into voice' to start. You'll see a green confirmation listing the files that got queued.",
      "Watch the 'Ingest jobs' card — it refreshes every few seconds and shows a progress bar and a 'running / succeeded' status for each run.",
      "Check the 'What's in your brand voice' card to confirm your files landed, with a count of chunks and characters per source.",
    ],
    tips: [
      "The Drive folder or files must be shared with the app's Google service account (or be link-accessible) — if nothing imports, that's almost always why.",
      "Audio and video are auto-transcribed at any length, so larger imports can take a while; the job stays 'running' until it finishes — leave the page and come back if needed.",
      "Re-importing the same file replaces its old version rather than adding a duplicate, so it's safe to re-ingest an updated doc.",
    ],
  },};
