-- Where a library photo came from, what it is, and whether it may be used.
--
-- The owner, 2026-10-08: "let apify scrape images from the brand first, then
-- store those images as the brand's". A scraped photo is not the same thing as
-- one the owner handed over, and nothing in media_assets could say so: there
-- was no origin, no rights, no size, and the only content hash was a 32-hex
-- tag. These columns carry that, so
--   * likeness paths (describe_hero_from_photos, the gpt-image-1 references)
--     can stay on photos the OWNER uploaded (origin = 'owner_upload'), and a
--     venue or food shot never becomes "the hero";
--   * the render pool can rank by quality and refuse screenshots and
--     thumbnails without re-downloading every photo to look at it;
--   * an owner upload and a scrape of the same picture are recognised as one.
--
-- ADDITIVE ONLY. Every column is ADD COLUMN IF NOT EXISTS with a default (or
-- NULL), nothing is dropped, renamed or rewritten, and existing URIs are left
-- exactly where they are — the URI is the key the photo-reuse ledger and stored
-- action payloads hold.

ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS width        integer;
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS height       integer;
-- portrait | landscape | square, written by the app from width/height (5% band).
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS orientation  text;
-- owner_upload | own_instagram | own_facebook | own_tiktok | own_linkedin |
-- stock | generated. Every row that exists today came from an owner upload or
-- was generated by us (source_type = 'generated' tells those two apart).
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS origin       text NOT NULL DEFAULT 'owner_upload';
-- The post the picture came from (permalink) and that platform's id for it.
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS origin_url   text NOT NULL DEFAULT '';
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS origin_ref   text NOT NULL DEFAULT '';
-- owner_attested (the owner uploaded it) | own_account (scraped from the
-- brand's OWN stated account) | stock_license | generated.
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS rights       text NOT NULL DEFAULT 'owner_attested';
-- When the photo was taken / posted, when the source says so. Freshness of a
-- photo is when it was made, not when we imported it.
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS taken_at     timestamptz;
-- The FULL 64-hex sha256 of the stored bytes. Legacy rows keep their 32-hex
-- 'sha256:' tag; readers compare against both (the tag is a prefix of this).
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS sha256       text;
-- 64-bit difference hash as 16 hex chars: near-duplicates (a re-encoded or
-- resized copy of the same picture) are within Hamming distance 6.
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS dhash        text;
-- Measured at ingest: {sharpness, short_edge, screenshot, in_rotation, reasons,
-- image_key}. Read by the render pool; never a reason to delete a row.
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS quality      jsonb NOT NULL DEFAULT '{}'::jsonb;
-- Does the picture show a person? NULL = not read yet.
ALTER TABLE media_assets ADD COLUMN IF NOT EXISTS has_person   boolean;

-- Vocabulary guards. NOT VALID first so a row written by some older path can
-- never block the migration; VALIDATE after, which only scans.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'media_assets_origin_check') THEN
    ALTER TABLE media_assets ADD CONSTRAINT media_assets_origin_check
      CHECK (origin IN ('owner_upload', 'own_instagram', 'own_facebook', 'own_tiktok',
                        'own_linkedin', 'stock', 'generated')) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'media_assets_rights_check') THEN
    ALTER TABLE media_assets ADD CONSTRAINT media_assets_rights_check
      CHECK (rights IN ('owner_attested', 'own_account', 'stock_license', 'generated')) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'media_assets_orientation_check') THEN
    ALTER TABLE media_assets ADD CONSTRAINT media_assets_orientation_check
      CHECK (orientation IS NULL OR orientation IN ('portrait', 'landscape', 'square')) NOT VALID;
  END IF;
END $$;

-- NO DATA BACKFILL. Rows we generated keep the 'owner_upload' default here and
-- are told apart by source_type = 'generated', which every reader already
-- filters on (hero_context, own_media.origin_of). An UPDATE in this file would
-- run with no app.current_tenant under FORCE ROW LEVEL SECURITY (034) and touch
-- no rows at all — a backfill that silently does nothing is worse than none.

ALTER TABLE media_assets VALIDATE CONSTRAINT media_assets_origin_check;
ALTER TABLE media_assets VALIDATE CONSTRAINT media_assets_rights_check;
ALTER TABLE media_assets VALIDATE CONSTRAINT media_assets_orientation_check;

-- The duplicate check runs on every import (exact hash within a tenant), and
-- the summary groups by origin. Not UNIQUE on purpose: legacy rows can share
-- bytes across roles, and the import path does its own locked check.
CREATE INDEX IF NOT EXISTS media_assets_tenant_sha256_idx
  ON media_assets (tenant_id, sha256) WHERE sha256 IS NOT NULL;
CREATE INDEX IF NOT EXISTS media_assets_tenant_origin_idx
  ON media_assets (tenant_id, origin);

-- What an own-post import PAID to read but kept no picture row for: a design
-- the renderer cannot draw, a read that was neither a layout nor a photograph,
-- or a template whose shape the brand (or the catalogue) already held. Without
-- it nothing in BM1 names that picture, so every re-send — a BM2 retry after
-- its own timeout, a lost ledger — buys the same gpt-4o read again. One row
-- per (tenant, picture); `body` is the verdict as first answered.
CREATE TABLE IF NOT EXISTS own_media_seen (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE
              DEFAULT current_setting('app.current_tenant', true)::uuid,
  origin      text NOT NULL,
  origin_ref  text NOT NULL DEFAULT '',
  image_key   text NOT NULL DEFAULT '',
  sha256      text NOT NULL,
  dhash       text NOT NULL DEFAULT '',
  verdict     text NOT NULL CHECK (verdict IN ('undrawable', 'template')),
  body        jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS own_media_seen_tenant_sha256_uq
  ON own_media_seen (tenant_id, sha256);
CREATE INDEX IF NOT EXISTS own_media_seen_tenant_ref_idx
  ON own_media_seen (tenant_id, origin, origin_ref, image_key) WHERE origin_ref <> '';

ALTER TABLE own_media_seen ENABLE ROW LEVEL SECURITY;
ALTER TABLE own_media_seen FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_media_seen_tenant ON own_media_seen;
CREATE POLICY own_media_seen_tenant ON own_media_seen USING
  (tenant_id = current_setting('app.current_tenant', true)::uuid);
