"""Question bank — bm2.0's seeded interview templates, shipped as data.

Ported verbatim from "brand manager 2.0"
backend/app/data/question_templates.json — the bank that
services/onboarding.seed_question_templates loaded into the donor's
question_templates table. james-os has no template table: intake_agent
materializes matching templates on demand into brand_questions rows (D3)
and joins a row back to its template by exact question text (falling back
to field_key), so the bank travels as code-reviewed data.

Template shape (the donor QuestionTemplate columns):
- id:            stable slug (the donor PK; kept for provenance)
- section:       bm2.0 profile section — becomes brand_questions.dimension
                 via manager.profile._SECTION_DIMENSION
- field_key:     the profile-envelope key a human answer writes to
- text:          the question as asked (ALSO the join key back from a
                 materialized brand_questions.question — do not edit texts
                 casually; edits orphan already-materialized rows)
- entity_types:  [] = universal; otherwise the entity types it applies to
- researchable:  False + info_value 5 = must-ask (only the human can answer)
- info_value / ask_priority: interview ranking inputs (D10 selection order)
"""

# james-os intake proposes kind person|asset|institution|politician
# (intake_agent.research_brand); the bank uses bm2.0 EntityType values.
KIND_TO_ENTITY_TYPE = {
    "person": "person",
    "company": "company",
    "asset": "physical_asset",
    "physical_asset": "physical_asset",
    "institution": "institution",
    "politician": "person",
}

TEMPLATES: list[dict] = [
    {'id': 'identity-display-name',
     'section': 'identity',
     'field_key': 'identity.display_name',
     'text': 'What name should we use publicly for this brand — exactly as it should appear in posts, bios, and captions?',
     'entity_types': [],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 40},
    {'id': 'identity-legal-name',
     'section': 'identity',
     'field_key': 'identity.legal_name',
     'text': 'What is the full legal name behind the brand (for press and compliance contexts), if different from the public name?',
     'entity_types': [],
     'researchable': True,
     'info_value': 2,
     'ask_priority': 95},
    {'id': 'identity-one-liner',
     'section': 'identity',
     'field_key': 'identity.positioning_one_liner',
     'text': "In one sentence, how would you introduce this brand to a stranger — who it's for and why it matters?",
     'entity_types': [],
     'researchable': True,
     'info_value': 5,
     'ask_priority': 45},
    {'id': 'identity-mission',
     'section': 'identity',
     'field_key': 'identity.mission',
     'text': "What is the mission — the change you're trying to make in the world beyond selling anything?",
     'entity_types': [],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'identity-story-person',
     'section': 'identity',
     'field_key': 'identity.story',
     'text': 'Tell us your story: where you started, the turning points, and how you got to where you are today.',
     'entity_types': ['person'],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 50},
    {'id': 'identity-story-company',
     'section': 'identity',
     'field_key': 'identity.story',
     'text': 'Tell us the founding story: why the company was started, by whom, and what problem it set out to solve.',
     'entity_types': ['company'],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 50},
    {'id': 'identity-story-asset',
     'section': 'identity',
     'field_key': 'identity.story',
     'text': 'Tell us the story of this property: its history, its character, and what makes people fall in love with it.',
     'entity_types': ['physical_asset'],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 50},
    {'id': 'identity-story-institution',
     'section': 'identity',
     'field_key': 'identity.story',
     'text': "Tell us the institution's story: its mandate, its defining milestones, and why it matters to the people it serves.",
     'entity_types': ['institution'],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 50},
    {'id': 'identity-locations',
     'section': 'identity',
     'field_key': 'identity.locations',
     'text': 'Where is the brand physically based or active — cities, regions, service areas?',
     'entity_types': [],
     'researchable': True,
     'info_value': 3,
     'ask_priority': 70},
    {'id': 'identity-key-people-person',
     'section': 'identity',
     'field_key': 'identity.key_people',
     'text': 'Who else is part of your public story — business partners, co-hosts, or family members who appear in your content?',
     'entity_types': ['person'],
     'researchable': True,
     'info_value': 3,
     'ask_priority': 75},
    {'id': 'identity-key-people-org',
     'section': 'identity',
     'field_key': 'identity.key_people',
     'text': 'Who are the public faces of the organization — founders, executives, or spokespeople who can appear in content?',
     'entity_types': ['company', 'institution'],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 60},
    {'id': 'identity-key-people-asset',
     'section': 'identity',
     'field_key': 'identity.key_people',
     'text': 'Who are the people behind the property — owners, managers, pros, or staff who could be featured in content?',
     'entity_types': ['physical_asset'],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 60},
    {'id': 'identity-holdings-person',
     'section': 'identity',
     'field_key': 'identity.holdings',
     'text': 'What ventures, board seats, brands, or properties are part of your portfolio that content could draw on?',
     'entity_types': ['person'],
     'researchable': True,
     'info_value': 5,
     'ask_priority': 35},
    {'id': 'identity-holdings-org',
     'section': 'identity',
     'field_key': 'identity.holdings',
     'text': 'What sub-brands, divisions, or affiliated ventures should content be able to reference?',
     'entity_types': ['company', 'institution'],
     'researchable': True,
     'info_value': 3,
     'ask_priority': 80},
    {'id': 'identity-founding',
     'section': 'identity',
     'field_key': 'identity.founding',
     'text': 'When was the brand founded or established, and are there anniversary dates worth commemorating in content?',
     'entity_types': [],
     'researchable': True,
     'info_value': 2,
     'ask_priority': 100},
    {'id': 'identity-roles-person',
     'section': 'identity',
     'field_key': 'identity.roles',
     'text': 'What are your current titles and roles — the credentials that should appear in bios and introductions?',
     'entity_types': ['person'],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'identity-asset-experience',
     'section': 'identity',
     'field_key': 'identity.experience',
     'text': 'Describe the experience of visiting in person — what do people see, feel, and remember after they leave?',
     'entity_types': ['physical_asset'],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 50},
    {'id': 'identity-name-pronunciation',
     'section': 'identity',
     'field_key': 'identity.pronunciation',
     'text': 'How is your name pronounced, and are there nicknames you embrace — or hate?',
     'entity_types': ['person'],
     'researchable': False,
     'info_value': 2,
     'ask_priority': 105},
    {'id': 'audience-target-segments',
     'section': 'audience',
     'field_key': 'audience.target_segments',
     'text': 'Who are the 2-3 audiences you most want your content to reach, in order of importance?',
     'entity_types': [],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 20},
    {'id': 'audience-demographics',
     'section': 'audience',
     'field_key': 'audience.demographics',
     'text': 'Describe your ideal audience member: age range, occupation, income level, and where they live.',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 75},
    {'id': 'audience-pains',
     'section': 'audience',
     'field_key': 'audience.pains',
     'text': 'What problems, frustrations, or fears keep your ideal audience up at night?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'audience-desires',
     'section': 'audience',
     'field_key': 'audience.desires',
     'text': 'What does your ideal audience member aspire to — what outcome are they really chasing?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'audience-current-gap',
     'section': 'audience',
     'field_key': 'audience.current',
     'text': 'Who actually follows you today, as far as you can tell — and does that match who you want?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 80},
    {'id': 'audience-aspirational',
     'section': 'audience',
     'field_key': 'audience.aspirational',
     'text': "Describe the audience you want two years from now that you don't have today.",
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 60},
    {'id': 'audience-geography',
     'section': 'audience',
     'field_key': 'audience.geography',
     'text': 'Is your audience local, regional, national, or global — and where should growth focus?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 75},
    {'id': 'audience-misconceptions',
     'section': 'audience',
     'field_key': 'audience.misconceptions',
     'text': 'What do people commonly get wrong or assume incorrectly about you or your brand?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 85},
    {'id': 'audience-decision-maker-company',
     'section': 'audience',
     'field_key': 'audience.decision_maker',
     'text': 'Who makes the buying decision for your product or service — and who influences them along the way?',
     'entity_types': ['company'],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 65},
    {'id': 'audience-visitor-asset',
     'section': 'audience',
     'field_key': 'audience.visitor_profile',
     'text': 'Who is your ideal guest — locals, tourists, members, event planners — and which group matters most for revenue?',
     'entity_types': ['physical_asset'],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 25},
    {'id': 'audience-stakeholders-institution',
     'section': 'audience',
     'field_key': 'audience.stakeholders',
     'text': 'Which stakeholder groups must your communications serve — the public, funders, policymakers, members — and who comes first when they conflict?',
     'entity_types': ['institution'],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 25},
    {'id': 'audience-exclusions',
     'section': 'audience',
     'field_key': 'audience.exclusions',
     'text': 'Is there any audience you deliberately do NOT want to attract?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 90},
    {'id': 'voice-tone-descriptors',
     'section': 'voice',
     'field_key': 'voice.tone_descriptors',
     'text': 'Pick 3-5 words that describe how the brand should sound (e.g. direct, warm, contrarian, playful, authoritative).',
     'entity_types': [],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 50},
    {'id': 'voice-signature-phrases',
     'section': 'voice',
     'field_key': 'voice.signature_phrases',
     'text': 'What phrases, sayings, or expressions do you use so often that people associate them with you?',
     'entity_types': [],
     'researchable': True,
     'info_value': 3,
     'ask_priority': 70},
    {'id': 'voice-banned-words',
     'section': 'voice',
     'field_key': 'voice.banned_words',
     'text': 'List the words and phrases we should never use in your content — jargon, clichés, slang, or anything that makes you cringe.',
     'entity_types': [],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 12},
    {'id': 'voice-humor',
     'section': 'voice',
     'field_key': 'voice.humor_level',
     'text': 'How much humor belongs in your content — none, light wit, regular jokes, full comedic? Is any kind of humor off the table?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 60},
    {'id': 'voice-exemplars',
     'section': 'voice',
     'field_key': 'voice.exemplars',
     'text': "Share 3-5 posts — yours or anyone's — that sound exactly the way you want this brand to sound.",
     'entity_types': [],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 30},
    {'id': 'voice-anti-exemplars',
     'section': 'voice',
     'field_key': 'voice.anti_exemplars',
     'text': "Show us something written about or for your brand that got the voice WRONG — and tell us what's off about it.",
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 85},
    {'id': 'voice-formality-person',
     'section': 'voice',
     'field_key': 'voice.formality',
     'text': 'When you talk to your audience, is it like a friend at a bar, a trusted advisor, or a keynote speaker?',
     'entity_types': ['person'],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 65},
    {'id': 'voice-formality-org',
     'section': 'voice',
     'field_key': 'voice.formality',
     'text': 'Should the brand write like a person or like an organization — and how formal, on a scale from boardroom to group chat?',
     'entity_types': ['company', 'institution', 'physical_asset'],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 65},
    {'id': 'voice-narrator',
     'section': 'voice',
     'field_key': 'voice.narrator',
     'text': "Who is speaking in your content — 'I' (a person), 'we' (a team), or the brand as its own character?",
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'voice-emoji',
     'section': 'voice',
     'field_key': 'voice.emoji_usage',
     'text': 'How do you feel about emojis, exclamation points, and hashtags — use freely, sparingly, or never?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 75},
    {'id': 'voice-visual-colors',
     'section': 'voice',
     'field_key': 'voice.visual_colors',
     'text': "What are your brand colors, fonts, and any visual do's and don'ts (logo usage, filters, styles to avoid)?",
     'entity_types': [],
     'researchable': True,
     'info_value': 3,
     'ask_priority': 80},
    {'id': 'voice-visual-templates',
     'section': 'voice',
     'field_key': 'voice.visual_templates',
     'text': 'Do you have existing design templates we should reuse, or should we establish a fresh visual system?',
     'entity_types': [],
     'researchable': False,
     'info_value': 2,
     'ask_priority': 100},
    {'id': 'voice-pet-peeves',
     'section': 'voice',
     'field_key': 'voice.pet_peeves',
     'text': "What writing habits instantly signal 'AI wrote this' or 'that's not me' — the things we must never do?",
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 45},
    {'id': 'voice-profanity',
     'section': 'voice',
     'field_key': 'voice.profanity',
     'text': "Where's your line on profanity and edgy language — never, mild when it lands, or anything goes?",
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 85},
    {'id': 'positioning-niche',
     'section': 'positioning',
     'field_key': 'positioning.niche',
     'text': "What category or niche should this brand own in people's minds — the thing you want to be THE name for?",
     'entity_types': [],
     'researchable': True,
     'info_value': 5,
     'ask_priority': 40},
    {'id': 'positioning-pillar-topics',
     'section': 'positioning',
     'field_key': 'positioning.pillar_topics',
     'text': 'List the 3-5 topics you want to consistently create content about.',
     'entity_types': [],
     'researchable': True,
     'info_value': 5,
     'ask_priority': 35},
    {'id': 'positioning-pillar-weights',
     'section': 'positioning',
     'field_key': 'positioning.pillar_weights',
     'text': 'Roughly what share of content should each of your main topics get (e.g. real estate 60%, mindset 20%, education 20%)?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 50},
    {'id': 'positioning-proof-points',
     'section': 'positioning',
     'field_key': 'positioning.proof_points',
     'text': 'What are your strongest proof points — press features, awards, board seats, rankings, verified predictions, notable clients?',
     'entity_types': [],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'positioning-credibility-ladder',
     'section': 'positioning',
     'field_key': 'positioning.credibility_ladder',
     'text': 'What appearances or recognitions would mark the next tier up for you — specific podcasts, stages, publications, or associations?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 60},
    {'id': 'positioning-differentiator',
     'section': 'positioning',
     'field_key': 'positioning.differentiator',
     'text': "Complete this sentence: 'Unlike others in my space, I/we...' — what genuinely sets this brand apart?",
     'entity_types': [],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 15},
    {'id': 'positioning-contrarian',
     'section': 'positioning',
     'field_key': 'positioning.contrarian_takes',
     'text': 'What do you believe about your industry that most of your peers would disagree with?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 65},
    {'id': 'positioning-predictions-person',
     'section': 'positioning',
     'field_key': 'positioning.predictions',
     'text': "What predictions have you made publicly that came true — or bold calls you're willing to put on the record now?",
     'entity_types': ['person'],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 80},
    {'id': 'positioning-authority-12mo',
     'section': 'positioning',
     'field_key': 'positioning.authority_target',
     'text': 'If one topic could be attached to your name in every search result 12 months from now, what would it be?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'positioning-asset-signature',
     'section': 'positioning',
     'field_key': 'positioning.signature_feature',
     'text': "What is the property's signature feature — the one thing every visitor photographs or tells friends about?",
     'entity_types': ['physical_asset'],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 60},
    {'id': 'positioning-institution-mandate',
     'section': 'positioning',
     'field_key': 'positioning.unique_mandate',
     'text': 'What is the institution uniquely mandated or positioned to do that no other organization can credibly claim?',
     'entity_types': ['institution'],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 60},
    {'id': 'positioning-enemy',
     'section': 'positioning',
     'field_key': 'positioning.enemy',
     'text': "What common practice, myth, or 'enemy' does the brand stand against?",
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 75},
    {'id': 'products-catalog-person',
     'section': 'products',
     'field_key': 'products.catalog',
     'text': 'What do you sell or offer — courses, services, speaking, books, deals, memberships? List everything, even the side offers.',
     'entity_types': ['person'],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 20},
    {'id': 'products-catalog-company',
     'section': 'products',
     'field_key': 'products.catalog',
     'text': 'List your products or services in order of strategic importance, with a one-line description of each.',
     'entity_types': ['company'],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 20},
    {'id': 'products-catalog-asset',
     'section': 'products',
     'field_key': 'products.catalog',
     'text': 'What can people buy or book at the property — rounds, memberships, events, lessons, dining, merchandise?',
     'entity_types': ['physical_asset'],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 20},
    {'id': 'products-catalog-institution',
     'section': 'products',
     'field_key': 'products.catalog',
     'text': 'What programs, services, or opportunities does the institution offer the public — and which need the most visibility?',
     'entity_types': ['institution'],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 20},
    {'id': 'products-primary-cta',
     'section': 'products',
     'field_key': 'products.primary_cta',
     'text': 'When someone loves a piece of your content, what is the ONE next step you want them to take?',
     'entity_types': [],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 18},
    {'id': 'products-funnels',
     'section': 'products',
     'field_key': 'products.funnels',
     'text': 'Walk us through your funnel(s): how does a stranger become a customer today, step by step?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'products-price-points',
     'section': 'products',
     'field_key': 'products.price_points',
     'text': 'What are your price points, from entry-level to premium?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 80},
    {'id': 'products-flagship',
     'section': 'products',
     'field_key': 'products.flagship',
     'text': 'Which single offer matters most to the business right now — the one content should ultimately drive?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 45},
    {'id': 'products-launches',
     'section': 'products',
     'field_key': 'products.launches',
     'text': 'Is anything launching, opening, or changing in the next 90 days that content should build toward?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 50},
    {'id': 'products-lead-magnet',
     'section': 'products',
     'field_key': 'products.lead_magnet',
     'text': 'Do you have free resources — whitepapers, guides, tools, a newsletter — that we can offer as calls to action?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 70},
    {'id': 'products-partnerships',
     'section': 'products',
     'field_key': 'products.partnerships',
     'text': 'Are there sponsors, partners, or affiliations that content must feature — or must never imply?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 75},
    {'id': 'products-events-asset',
     'section': 'products',
     'field_key': 'products.events',
     'text': 'What recurring events — tournaments, leagues, weddings, seasonal programs — anchor your calendar each year?',
     'entity_types': ['physical_asset'],
     'researchable': True,
     'info_value': 3,
     'ask_priority': 65},
    {'id': 'competitors-aspirational',
     'section': 'competitors',
     'field_key': 'competitors.aspirational',
     'text': "Name 3-5 accounts or brands you'd like to be compared to or want to become.",
     'entity_types': [],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 10},
    {'id': 'competitors-direct',
     'section': 'competitors',
     'field_key': 'competitors.direct',
     'text': 'Who are your direct competitors — the accounts or businesses your audience compares you to today?',
     'entity_types': [],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 50},
    {'id': 'competitors-collab',
     'section': 'competitors',
     'field_key': 'competitors.collab_targets',
     'text': 'Which accounts, creators, or organizations would you love to collaborate with or be featured by?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 70},
    {'id': 'competitors-anti',
     'section': 'competitors',
     'field_key': 'competitors.anti_peers',
     'text': 'Is there anyone you do NOT want to be compared to or associated with, even implicitly?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 80},
    {'id': 'competitors-local-asset',
     'section': 'competitors',
     'field_key': 'competitors.local',
     'text': "Which nearby venues compete for your guests' time and money — and what do they do better or worse than you?",
     'entity_types': ['physical_asset'],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'competitors-admired',
     'section': 'competitors',
     'field_key': 'competitors.admired',
     'text': 'Whose content do you personally admire — even outside your industry — and what about it do you admire?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 85},
    {'id': 'competitors-peer-gap',
     'section': 'competitors',
     'field_key': 'competitors.peer_gap',
     'text': 'What do your bigger competitors get attention for that you believe you actually do better?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 75},
    {'id': 'competitors-institution-peers',
     'section': 'competitors',
     'field_key': 'competitors.benchmark_institutions',
     'text': 'Which peer institutions do you benchmark against — and which do you consider a tier above you?',
     'entity_types': ['institution'],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'goals-business-primary',
     'section': 'goals',
     'field_key': 'goals.business_primary',
     'text': 'What is the single most important business outcome social media should drive this year — leads, sales, bookings, donations, or authority?',
     'entity_types': [],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 14},
    {'id': 'goals-follower-targets',
     'section': 'goals',
     'field_key': 'goals.follower_targets',
     'text': 'Do you have specific follower or subscriber targets per platform? If so, what are they and by when?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'goals-engagement-targets',
     'section': 'goals',
     'field_key': 'goals.engagement_targets',
     'text': 'Beyond follower counts, what engagement matters most to you — comments, shares, DMs, watch time?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 70},
    {'id': 'goals-lead-targets',
     'section': 'goals',
     'field_key': 'goals.lead_targets',
     'text': 'How many leads, inquiries, or conversions per month would make this effort clearly worth it?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 60},
    {'id': 'goals-timeframe',
     'section': 'goals',
     'field_key': 'goals.timeframe',
     'text': "What's your time horizon — do you need visible results in 90 days, or are you building for 2+ years?",
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 50},
    {'id': 'goals-priority-weights',
     'section': 'goals',
     'field_key': 'goals.priority_weights',
     'text': 'If audience growth, revenue, and reputation ever pull in different directions, how would you rank them?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 65},
    {'id': 'goals-motivation',
     'section': 'goals',
     'field_key': 'goals.motivation',
     'text': "Why now? What's driving the investment in this brand at this particular moment?",
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 80},
    {'id': 'goals-success-90d',
     'section': 'goals',
     'field_key': 'goals.success_90d',
     'text': 'Describe what a wildly successful first 90 days looks like, in your own words.',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 45},
    {'id': 'goals-time-budget',
     'section': 'goals',
     'field_key': 'goals.time_budget',
     'text': 'How much of your own time per week can you realistically give — filming, approving, appearing?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 40},
    {'id': 'goals-appearance-targets-person',
     'section': 'goals',
     'field_key': 'goals.appearance_targets',
     'text': 'Are there specific stages, podcasts, or media outlets you want to land in the next 12 months?',
     'entity_types': ['person'],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 75},
    {'id': 'goals-occupancy-asset',
     'section': 'goals',
     'field_key': 'goals.occupancy_targets',
     'text': 'What are your capacity or occupancy goals — tee times, events, memberships — and which season needs the most help?',
     'entity_types': ['physical_asset'],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'goals-participation-institution',
     'section': 'goals',
     'field_key': 'goals.participation_targets',
     'text': 'What fundraising, enrollment, attendance, or participation targets should communications support this year?',
     'entity_types': ['institution'],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'goals-recruiting-company',
     'section': 'goals',
     'field_key': 'goals.recruiting',
     'text': 'Is attracting talent a goal for your content — should some of it deliberately target future employees?',
     'entity_types': ['company'],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 80},
    {'id': 'guardrails-off-limits',
     'section': 'guardrails',
     'field_key': 'guardrails.off_limits',
     'text': 'What topics are completely off-limits for this brand — subjects we should never post about, joke about, or comment on?',
     'entity_types': [],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 11},
    {'id': 'guardrails-mandatory-approval',
     'section': 'guardrails',
     'field_key': 'guardrails.mandatory_approval',
     'text': 'Which types of content must ALWAYS get your explicit approval before publishing (e.g. anything touching politics, pricing, clients, or breaking news)?',
     'entity_types': [],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 13},
    {'id': 'guardrails-compliance',
     'section': 'guardrails',
     'field_key': 'guardrails.compliance',
     'text': 'Are there legal or regulatory rules your content must follow — licensing disclosures, financial-advice restrictions, industry regulations?',
     'entity_types': [],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 16},
    {'id': 'guardrails-autonomy',
     'section': 'guardrails',
     'field_key': 'guardrails.autonomy_tier',
     'text': 'How much should the system do without you: draft-only, auto-publish safe evergreen content, or auto-publish everything?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 40},
    {'id': 'guardrails-politics',
     'section': 'guardrails',
     'field_key': 'guardrails.politics_stance',
     'text': 'Where do you stand on political and social-issue content — lean in deliberately, respond only when it touches your niche, or avoid entirely?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 45},
    {'id': 'guardrails-competitor-mentions',
     'section': 'guardrails',
     'field_key': 'guardrails.competitor_mentions',
     'text': 'May content name competitors directly — in comparisons, commentary, or criticism — or should they stay unnamed?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 70},
    {'id': 'guardrails-complaints',
     'section': 'guardrails',
     'field_key': 'guardrails.complaint_handling',
     'text': "When someone complains or criticizes publicly, what's the standing rule — respond, escalate to you, or ignore?",
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 75},
    {'id': 'guardrails-crisis',
     'section': 'guardrails',
     'field_key': 'guardrails.crisis_protocol',
     'text': "If something goes wrong publicly, who must be looped in immediately — and is there a standing 'go quiet' rule?",
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 85},
    {'id': 'guardrails-privacy-person',
     'section': 'guardrails',
     'field_key': 'guardrails.privacy_boundaries',
     'text': 'What parts of your personal life are shareable — family, health, finances, relationships — and what stays private, always?',
     'entity_types': ['person'],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 17},
    {'id': 'guardrails-privacy-org',
     'section': 'guardrails',
     'field_key': 'guardrails.privacy_boundaries',
     'text': 'What internal matters are never content — personnel, financials, client or member identities, security details?',
     'entity_types': ['company', 'institution', 'physical_asset'],
     'researchable': False,
     'info_value': 5,
     'ask_priority': 17},
    {'id': 'guardrails-banned-imagery',
     'section': 'guardrails',
     'field_key': 'guardrails.banned_imagery',
     'text': 'Are there images or visual situations to avoid — old logos, certain people, competitor products, specific locations?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 80},
    {'id': 'guardrails-claims',
     'section': 'guardrails',
     'field_key': 'guardrails.claims_policy',
     'text': "What claims require proof before we publish — results, statistics, health or financial outcomes, superlatives like 'best' or '#1'?",
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 50},
    {'id': 'guardrails-tone-redlines',
     'section': 'guardrails',
     'field_key': 'guardrails.tone_redlines',
     'text': 'Is there any tone we must never take, even if it performs well — rage bait, self-deprecation, fear tactics?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'channels-active',
     'section': 'channels',
     'field_key': 'channels.active_platforms',
     'text': 'Which social platforms is the brand on today — and which one matters most to you personally?',
     'entity_types': [],
     'researchable': True,
     'info_value': 4,
     'ask_priority': 45},
    {'id': 'channels-handles',
     'section': 'channels',
     'field_key': 'channels.handles',
     'text': 'List your exact handles or profile URLs on every platform, including accounts you no longer use.',
     'entity_types': [],
     'researchable': True,
     'info_value': 3,
     'ask_priority': 60},
    {'id': 'channels-website',
     'section': 'channels',
     'field_key': 'channels.website',
     'text': 'What is your primary website — and are there other owned properties like landing pages, microsites, or blogs?',
     'entity_types': [],
     'researchable': True,
     'info_value': 3,
     'ask_priority': 65},
    {'id': 'channels-newsletter',
     'section': 'channels',
     'field_key': 'channels.newsletter',
     'text': 'Do you have a newsletter or Substack — and should social content drive subscriptions to it?',
     'entity_types': [],
     'researchable': True,
     'info_value': 3,
     'ask_priority': 70},
    {'id': 'channels-press-page',
     'section': 'channels',
     'field_key': 'channels.press_page',
     'text': 'Is there a page that collects your press coverage and media mentions? Share the URL.',
     'entity_types': [],
     'researchable': True,
     'info_value': 2,
     'ask_priority': 90},
    {'id': 'channels-asset-library',
     'section': 'channels',
     'field_key': 'channels.asset_library',
     'text': 'Where do your existing photos, videos, and brand assets live — and can we get access?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 40},
    {'id': 'channels-platform-priority',
     'section': 'channels',
     'field_key': 'channels.platform_priority',
     'text': 'If we could only grow ONE platform for the next 90 days, which would you choose — and why that one?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 50},
    {'id': 'channels-dormant',
     'section': 'channels',
     'field_key': 'channels.dormant_accounts',
     'text': 'Are there old or abandoned accounts we should revive, ignore, or shut down?',
     'entity_types': [],
     'researchable': True,
     'info_value': 2,
     'ask_priority': 95},
    {'id': 'channels-email-list',
     'section': 'channels',
     'field_key': 'channels.email_list',
     'text': 'Do you have an email list — roughly how big is it, and how often do you mail it?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 75},
    {'id': 'performance-best-content',
     'section': 'performance',
     'field_key': 'performance.best_content',
     'text': 'What content has performed best for you historically — and why do you think it worked?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 50},
    {'id': 'performance-worst-content',
     'section': 'performance',
     'field_key': 'performance.worst_content',
     'text': "What have you tried that flopped or felt wrong — content you'd never want repeated?",
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 55},
    {'id': 'performance-experiments',
     'section': 'performance',
     'field_key': 'performance.experiments',
     'text': 'What experiments have you run — formats, posting times, series — and what did you learn from them?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 75},
    {'id': 'performance-past-efforts',
     'section': 'performance',
     'field_key': 'performance.past_efforts',
     'text': 'Have you worked with agencies, ghostwriters, or tools before? What did they get right — and wrong?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 80},
    {'id': 'performance-cadence-history',
     'section': 'performance',
     'field_key': 'performance.cadence_history',
     'text': 'What has your posting rhythm actually been over the past year — consistent, in bursts, or dormant?',
     'entity_types': [],
     'researchable': False,
     'info_value': 2,
     'ask_priority': 90},
    {'id': 'performance-top-posts',
     'section': 'performance',
     'field_key': 'performance.top_posts',
     'text': "Link 3-5 of your own posts you're proudest of, regardless of how they performed.",
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 60},
    {'id': 'performance-audience-feedback',
     'section': 'performance',
     'field_key': 'performance.audience_feedback',
     'text': 'What do people say to you in person or in DMs that never shows up in your metrics?',
     'entity_types': [],
     'researchable': False,
     'info_value': 3,
     'ask_priority': 85},
    {'id': 'performance-content-backlog',
     'section': 'performance',
     'field_key': 'performance.content_backlog',
     'text': 'Do you have unused recordings, long-form videos, interviews, or writing we could mine for content?',
     'entity_types': [],
     'researchable': False,
     'info_value': 4,
     'ask_priority': 45},
]

_BY_TEXT = {t["text"]: t for t in TEMPLATES}  # texts are unique (asserted at build)


def templates_for(entity_type: str | None) -> list[dict]:
    """Templates matching the brand's entity type (D3): universal templates
    always; typed templates only once the type is known and matches."""
    et = KIND_TO_ENTITY_TYPE.get((entity_type or "").strip().lower(), "")
    return [t for t in TEMPLATES if not t["entity_types"] or (et and et in t["entity_types"])]


def template_for(question: str, field_key: str = "") -> dict | None:
    """The template behind a brand_questions row. Exact-text match first
    (materialization inserts template text verbatim); falls back to the
    field_key — preferring the universal variant when several templates
    share a key. None for non-template rows (contradiction questions from
    manager.profile, or legacy v1 LLM-generated questions)."""
    tmpl = _BY_TEXT.get(question)
    if tmpl is not None and (not field_key or tmpl["field_key"] == field_key):
        return tmpl
    if field_key:
        matches = [t for t in TEMPLATES if t["field_key"] == field_key]
        for t in matches:
            if not t["entity_types"]:
                return t
        return matches[0] if matches else None
    return tmpl


__all__ = ["KIND_TO_ENTITY_TYPE", "TEMPLATES", "templates_for", "template_for"]
